module.exports = {
  preset: 'jest-preset-angular',
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  testMatch: ['<rootDir>/src/**/*.spec.ts'],
  coveragePathIgnorePatterns: [
    '<rootDir>/src/main.ts',
    '<rootDir>/src/index.html',
    '<rootDir>/src/app/app.config.ts',
    '<rootDir>/src/app/app.routes.ts',
    '<rootDir>/src/app/core/',
    '<rootDir>/src/environments/',
    '<rootDir>/src/app/features/converter/data-access/',
    '<rootDir>/src/app/features/converter/domain/',
    '<rootDir>/src/app/features/converter/state/',
    '<rootDir>/src/app/features/converter/pages/converter-page.component.ts',
    '<rootDir>/src/app/features/converter/ui/code-preview-panel.component.ts',
    '<rootDir>/src/app/features/converter/ui/code-preview-tabs.component.ts',
    '<rootDir>/src/app/features/converter/ui/file-tree.component.ts',
    '<rootDir>/src/app/features/converter/ui/status-chip.component.ts',
    '<rootDir>/src/app/features/legacy2-modern/data-access/',
    '<rootDir>/src/app/features/legacy2-modern/domain/',
  ],
  coverageThreshold: {
    global: {
      statements: 90,
      branches: 90,
    },
  },
};
